### ISSUE TITLE
Move this repository over to GoogleCloudPlatform organization?

### ISSUE THREAD

**Issue by jgeewax** [dhermes/gcloud-python-bigtable#17]
Should we leave here in personal-land or move over to GCP? If it's something we want to let customers play with while we're in limbo about merging into gcloud-python, might be worthwhile to move. If it's not intended to actually be used, then we can leave it here...?

**Comment by dhermes** [comment]
It depends on the discussions about breaking up `gcloud-python` into small repos.

This should be reviewed in full before it gets the "endorsement" of GCP.

**Comment by dhermes** [comment]
Closing here since https://github.com/GoogleCloudPlatform/gcloud-python/issues/1212 exists
