### ISSUE TITLE
support for grpc/grpcio 0.12.0

### ISSUE THREAD

**Issue by bjorndv** [dhermes/gcloud-python-bigtable#23]
I can not use the bigtable client anymore as it seems that grpc._adapter._c does not exist anymore (it has been moved in the newest version of grpc). Would it be possible to support this new version of grpc?

**Comment by dhermes** [comment]
Thanks for the heads up. It may be easiest just to pin to version `0.11.0b1` for now, but we definitely plan to upgrade to `0.12.0b0` soon.

**Comment by dhermes** [comment]
Skipped over it and got in `0.13.0`
