### ISSUE TITLE
Didn't we decide that using `filter` as a param name was bad?

### ISSUE THREAD

**Issue by jgeewax** [dhermes/gcloud-python-bigtable#8]
Referring to: http://gcloud-python-bigtable.readthedocs.org/en/data-api-complete/data-api.html#conditional-mutations

Pretty sure in the resource-manager API for gcloud-python we said that using `method(filter=filter)` was a bad way to go.

**Comment by dhermes** [comment]
It makes me uncomfortable using `filter`. I think the standard recommendation is to use `filter_`. (In general when `foo` is a builtin keyword then `foo_` should be used.)

/cc @tseaver

**Comment by tseaver** [comment]
For actual keywords, we wouldn't have a choice:  for builtins, adding the underscore seems right, if we can't see a better spelling.  We got away without the underscore in `datastore` because the query held /passed `filters`, rather than a single `filter`.

**Comment by dhermes** [comment]
Should we add `filter`, `open` and others to `bad-names` in our PyLint config (which this project shares)?

**Comment by dhermes** [comment]
Similar question, is `filter` acceptable as a `@property`. As far as I'm concerned the answer is yes since `foo.filter` will never be in the global namespace. But, I can be persuaded.

**Comment by dhermes** [comment]
@tseaver I mostly resolved this with 86bb23bf5f1b6f475be2bf050bde91fc3dce55f3.

However, there is still the issue of `Row.filter`. I forget, did we decide to keep it or ditch it?

**Comment by tseaver** [comment]
`filter` as an attribute can never shadow the built-in, so I'm fine with it.

**Comment by dhermes** [comment]
Cool. Closing this.
